stages:
    - analysis
    - test
    - coverage

isort:
    tags:
        - python2
    stage: analysis
    before_script:
        - pip install isort
        - pip list
    script: "make check-isort"

flake8:
    tags:
        - python2
    stage: analysis
    before_script:
        - pip install flake8
        - pip list
    script: "make check-flake8"

pydocstyle:
    tags:
        - python2
    stage: analysis
    before_script:
        - pip install pydocstyle!=2.1.0
        - pip list
    script: "make check-doc"

test:
    tags:
        - python2
    stage: test
    script:
        # Install coverage
        - pip install coverage
        - mkdir coverage
        # install omniORB and omniIDL
        - apt-get update && apt-get install -y python-omniorb omniidl-python
        - pip install -r requirements-dev.txt
        - pip list
        - make test-coverage
    artifacts:
        expire_in: 1d
        paths:
        - coverage/
    variables:
        COVERAGE_FILE: "coverage/.coverage.$CI_BUILD_ID"

coverage-report:
    tags:
        - python2
    stage: coverage
    script:
        - pip install coverage
        - coverage combine coverage/
        - coverage report --include=*/tests/* --fail-under=100
        - coverage report
