stages:
    - analysis
    - test
    - coverage

isort:
    image: cznic/ubuntu_python_runner:latest
    stage: analysis
    before_script:
        - pip install isort
        - pip list
    script: "make check-isort"

flake8:
    image: cznic/ubuntu_python_runner:latest
    stage: analysis
    before_script:
        - pip install flake8
        - pip list
    script: "make check-flake8"

test:
    image: cznic/ubuntu_python_runner:latest
    stage: test
    script:
        # Install coverage
        - pip install coverage
        - mkdir coverage
        # install omniORB and omniIDL
        - apt-get update && apt-get install -y python-omniorb omniidl-python
        # freddist are required to install our dependencies
        - pip install -e git+git@gitlab.office.nic.cz:utils/freddist.git#egg=freddist
        - pip install -r requirements-dev.txt
        - pip list
        - make test-coverage
    artifacts:
        expire_in: 1d
        paths:
        - coverage/
    variables:
        COVERAGE_FILE: "coverage/.coverage.$CI_BUILD_ID"

coverage-report:
    image: cznic/ubuntu_python_runner:latest
    stage: coverage
    script:
        - pip install coverage
        - coverage combine coverage/
        - coverage report --include=*/tests/* --fail-under=100
        - coverage report
