variables:
    # Add path to the IDL directory
    PYTHONPATH: ":idl"

stages:
    - analysis
    - test

########################################################################################################################
# Basic declarations
.requires-python: &requires-python
    tags:
        - python

.python2-xenial: &python2-xenial
    image: cznic/ubuntu_xenial_python2:latest

.test: &test
    <<: *requires-python
    <<: *python2-xenial
    stage: test
    before_script:
        # Install package dependencies
        - apt-get update && apt-get install -y omniidl-python python-omniorb
        # Get pr-version and update IDL requirements
        - git clone git@gitlab.office.nic.cz:pr-utils/pr-version.git --depth 1
        - if [ -e pr-version/devel/$CI_BUILD_REF_NAME.conf ]; then IDL_BRANCH=$(python -c "import json;obj=json.load(open('pr-version/devel/${CI_BUILD_REF_NAME}.conf'));print obj.get('idl',{}).get('revision', 'master')"); fi
        - git clone git@gitlab.office.nic.cz:fred/idl.git
        - (cd idl && git checkout $IDL_BRANCH && omniidl -bpython -Wbmodules=fred_idl -Wbstubs=fred_idl._stubs idl/*.idl)
        - pip install tox
        - pip install git+https://github.com/balabit/tox-debian-plugin.git
    script:
        - tox


########################################################################################################################
# Individual jobs
quality:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    before_script:
        - pip install tox
    script:
        - tox -e quality

depcheck:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    only:
        - schedules
    before_script:
        # Install package with testing dependencies to verify versions
        - pip install --process-dependency-links .[testing]
    script:
        - check-constraints.py constraints.txt
    allow_failure: true

test:
    <<: *test

test-thawed:
    <<: *test
    only:
        - schedules
    script:
        - tox -e thaw
