stages:
    - analysis
    - test
    - coverage

########################################################################################################################
# Basic declarations
.requires-python: &requires-python
    tags:
        - python

.python2-xenial: &python2-xenial
    image: cznic/ubuntu_xenial_python2:latest

.test: &test
    <<: *requires-python
    <<: *python2-xenial
    stage: test
    before_script:
        # Install package dependencies
        - apt-get update && apt-get install -y omniidl-python python-omniorb
        - pip install -r requirements-dev.txt coverage
        - pip list
    script:
        - mkdir coverage
        - make test-coverage
    artifacts:
        expire_in: 1d
        paths:
        - coverage/
    variables:
        COVERAGE_FILE: "coverage/.coverage.$CI_BUILD_ID"

########################################################################################################################
# Individual jobs
isort:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    before_script:
        - pip install isort
        - pip list
    script: "make check-isort"

flake8:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    before_script:
        - pip install flake8
        - pip list
    script: "make check-flake8"

pydocstyle:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    before_script:
        - pip install pydocstyle
        - pip list
    script: "make check-doc"

test:
    <<: *test

coverage-report:
    <<: *requires-python
    <<: *python2-xenial
    stage: coverage
    script:
        - pip install coverage
        - pip list
        - coverage combine coverage/
        - coverage report --include=*/tests/* --fail-under=100
        - coverage report --omit=*/tests/*
